### ISSUE TITLE
Suggest comment line on source code

### ISSUE THREAD

**Issue by hg-pyun** [lacti/node-simple-rpc#1]
I think it would be nice to comment the source code. like [mimipack].(https://github.com/ronami/minipack/blob/master/src/minipack.js)

Thank you :D

**Comment by lacti** [comment]
Sorry, I'm late.
That's a great idea. I will write soon many of comments for that.

Thanks :)

**Comment by lacti** [comment]
I think I do my best to write comments on the source code. Please feel free let me know about the place that needs to more comments. If so, I will reopen this issue and I try to write more comments for that.

Thank you :)
